# Default values for helm-tp4.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []


resources: {}

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}

volumes:
  - mariadb:
    name: maria-db
    pv_size: 10Gi
    path: /data/mariadb
    persistentVolumeReclaimPolicy: Retain
    pvc_size: 1Gi
    volumeName: maria-db
  - web:
    name: web
    pv_size: 10Gi
    path: /data/web
    persistentVolumeReclaimPolicy: Retain
    pvc_size: 1Gi
    volumeName: web

web:
  volumeMount:
    name: web
    mountPath: /srv/app/pvc
  volumes:
    name: web
    claimName: web
  service:
    type: ClusterIP
    port: 80
    name: web
  replicaCount: 1
  image:
    repository: codebuds/deno-webserver
    pullPolicy: IfNotPresent
    tag: 1.5.0

mariadb:
  rootPassword: asecret
  user: root
  password: asecret
  database: logs
  image:
    repository: mariadb
    pullPolicy: Always
    tag: "10.7"
  volumeMount:
    name: maria-db
    mountPath: /var/lib/mysql
  volumes:
    name: maria-db
    claimName: maria-db
  service:
    name: maria-db
