apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.web.service.name }}
  labels:
    {{- include "helm-tp4.labels" . | nindent 4 }}
spec:
  type: {{ .Values.web.service.type }}
  ports:
    - port: {{ .Values.web.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "helm-tp4.selectorLabels" . | nindent 4 }}

---

apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.mariadb.service.name }}
spec:
  ports:
    - port: 3306
  selector:
    app: {{ .Values.mariadb.service.name }}
